name: Deploy Static Portal


on:
  workflow_dispatch:  
    debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
  push:
    branches: 
      - apifiltering

jobs:
  generate-portal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name : checkout-repo
      id: checkout-repo  
      
    - name: Zip files
      run: zip -qq -r portal-input.zip . -x admin-APIMATIC-BUILD.json
      
    - name: Extract generated Portal
      run: unzip -qq portal-input.zip -d static-portal
      
    - name: list 
      run: ls
